name: Immutable dependencies

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  immutable-dependencies:
    uses: Albert-Maxwell/.github/.github/workflows/immutable-dependencies.yml@c419e8503d2c50ce68f7df75f1936721b9d83a52
